version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: progulkas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/progulkas?schema=public
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: development-secret-change-me
      GOOGLE_CLIENT_ID: ""
      GOOGLE_CLIENT_SECRET: ""
      EMAIL_SERVER_HOST: ""
      EMAIL_SERVER_PORT: ""
      EMAIL_SERVER_USER: ""
      EMAIL_SERVER_PASSWORD: ""
      EMAIL_FROM: ""
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - node-modules:/app/node_modules

volumes:
  postgres-data:
  node-modules:
